- name: Update apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: install dotnet
  apt:
    name:
      - dotnet6
      - aspnetcore-runtime-6.0
    state: present
  become: yes
  become_user: root
