# install right version of python
- name: Update apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: install software properties common
  apt:
    name: software-properties-common
    state: present

- name: add repository for python3.8
  expect:
    command: sudo add-apt-repository ppa:deadsnakes/ppa
    responses:
      "Press*": ""
  become: true
  become_user: root

- name: install python3.8
  apt:
    name: python3.8
    state: present
