- name: fetch latest versin of ripgrep
  shell: curl -s "https://api.github.com/repos/BurntSushi/ripgrep/releases/latest" | grep "tag_name"
  register: json_row

- name: extract version
  set_fact:
    ripgrep_version: "{{ json_row.stdout | regex_search('.*?([0-9.]+)', '\\1') | first }}"

- name: fetch ripgrep tar archive
  shell: 'curl -Lo /tmp/ripgrep.deb "https://github.com/BurntSushi/ripgrep/releases/latest/download/ripgrep_{{ ripgrep_version }}_amd64.deb"'

- name: install ripgrep
  apt:
    deb: /tmp/ripgrep.deb
  become: yes
  become_user: root

- name: clean up ripgrep
  file:
    path: /tmp/ripgrep.deb
    state: absent

