---

# Preparations
# 1. Ensure that you have agent forwarding in your ~/.ssh/config file
# 2. Ensure that you have started a private ssh key that give access to all git repositories in this playbook
# 3. trigger sudo by e.g. "sudo ls"
# 4. run with
# ansible-playbook -i /home/edvard/sources/admin/ansible/inventories/local_inventory windows.yml
#   local-inventory is configured to run on self!
# (old way) ansible-playbook --connection=local --inventory=127.0.0.1, --limit 127.0.0.1 self.yml

# (alternative), create a key-pair, put the public key into
# /root/.ssh/authorized_keys/. Then ansible can login as root.

# (old way) - hosts: 127.0.0.1
- hosts: self
  gather_facts: false
  vars:
    os_branch_name: "wsl"
  roles:
    - role: init
    - role: windows_fixes
    - role: vim
      tags: vim
    - role: tmux
      tags: tmux
    - role: administration
