

- name: Install node trough homebrew
  become: yes
  become_user: edvard
  community.general.homebrew:
    name: node
    state: present

# See also https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install
- name: Install yarn trough homebrew
  become: yes
  become_user: edvard
  community.general.homebrew:
    name: yarn
    state: present

- name: install lazygit through homebrew
  # requires: ansible-galaxy collection install community.general
  become: yes
  become_user: edvard
  community.general.homebrew:
    name: lazygit
    state: present

- name: Install tig through homebrew
  become: yes
  become_user: edvard
  community.general.homebrew:
    name: tig
    state: present

- name: install emacs
  apt:
    name: emacs25
    state: present

- name: download fzf git repo
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest: /home/edvard/.fzf
    update: no
  tags: fzf

- name: install fzf
  become: yes
  become_user: edvard
  command: /home/edvard/.fzf/install --all
  tags: fzf

