
- name: Remove previous downloaded installfile (idempotence)
  file:
    path: /tmp/homebrew_install.sh
    state: absent
  tags: now

- name: download homebrew
  become: yes
  become_user: edvard
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: /tmp/homebrew_install.sh
    mode: '0550'
  tags: now

- name: Install homebrew
  become: yes
  become_user: edvard
  command: /tmp/homebrew_install.sh 
  tags: now

- name: Activate homebrew without restarting
  become: yes
  become_user: edvard
  command: /home/linuxbrew/.linuxbrew/bin/brew shellenv 
  tags: now

- name: install emacs
  apt:
    name: emacs25
    state: present

- name: download fzf git repo
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest: /home/edvard/.fzf
    update: no
  tags: fzf

- name: install fzf
  become: yes
  become_user: edvard
  command: /home/edvard/.fzf/install --all
  tags: fzf

- name: fetch lazygit
  become: yes
  become_user: edvard
  get_url:
    url: https://github.com/jesseduffield/lazygit/releases/download/v0.31.4/lazygit_0.31.4_Linux_x86_64.tar.gz
    dest: /home/edvard/bin/lazygit
    mode: '0550'

