

- name: Install node trough homebrew
  community.general.homebrew:
    name: node
    state: present
    path: '/home/linuxbrew/.linuxbrew/bin'

# See also https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install
- name: Install yarn trough homebrew
  community.general.homebrew:
    name: yarn
    state: present
    path: '/home/linuxbrew/.linuxbrew/bin'

- name: install lazygit through homebrew
  # requires: ansible-galaxy collection install community.general
  community.general.homebrew:
    name: lazygit
    state: present
    path: '/home/linuxbrew/.linuxbrew/bin'

- name: Install tig through homebrew
  community.general.homebrew:
    name: tig
    state: present
    path: '/home/linuxbrew/.linuxbrew/bin'

- name: install emacs
  become: true
  apt:
    name: emacs
    state: present

- name: download fzf git repo
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest: "{{ self_user }}/.fzf"
    update: no
  tags: fzf

- name: install fzf
  command: "{{ self_user }}/.fzf/install --all"
  tags: fzf

