- name: install common packages
  apt:
    name: "{{ item }}"
  loop:
    - ack

- name: install emacs
  apt:
    name: emacs25
    state: present

- name: download fzf git repo
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest: /home/edvard/.fzf
    update: no
  tags: fzf

- name: install fzf
  become: yes
  become_user: edvard
  command: /home/edvard/.fzf/install --all
  tags: fzf
