
- name: Remove previous downloaded installfile (idempotence)
  file:
    path: /tmp/homebrew_install.sh
    state: absent

- name: download homebrew
  become: yes
  become_user: edvard
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: /tmp/homebrew_install.sh
    mode: '0550'

- name: Install homebrew
  become: yes
  become_user: edvard
  command: /tmp/homebrew_install.sh 

- name: Activate homebrew without restarting
  become: yes
  become_user: edvard
  command: /home/linuxbrew/.linuxbrew/bin/brew shellenv 

- name: install lazygit through homebrew
  # requires: ansible-galaxy collection install community.general
  become: yes
  become_user: edvard
  community.general.homebrew:
    name: lazygit
    state: present
  tags: now

- name: install emacs
  apt:
    name: emacs25
    state: present

- name: download fzf git repo
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest: /home/edvard/.fzf
    update: no
  tags: fzf

- name: install fzf
  become: yes
  become_user: edvard
  command: /home/edvard/.fzf/install --all
  tags: fzf

