- name: Remove previous downloaded installfile (idempotence)
  file:
    path: /tmp/homebrew_install.sh
    state: absent

- name: download homebrew
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: /tmp/homebrew_install.sh
    mode: '0750'

- name: Install homebrew
  command: /tmp/homebrew_install.sh

- name: Activate homebrew without restarting
  shell: /home/linuxbrew/.linuxbrew/bin/brew shellenv

- name: Add brew into global PATH environment variable
  become: true
  copy:
    dest: /etc/profile.d/brew_path.sh
    content: 'PATH=$PATH:/home/linuxbrew/.linuxbrew/bin'

- name: Install node trough homebrew
  community.general.homebrew:
    name: node
    state: present
    path: '/home/linuxbrew/.linuxbrew/bin'

# See also https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install
- name: Install yarn trough homebrew
  community.general.homebrew:
    name: yarn
    state: present
    path: '/home/linuxbrew/.linuxbrew/bin'

- name: install lazygit through homebrew
  # requires: ansible-galaxy collection install community.general
  community.general.homebrew:
    name: lazygit
    state: present
    path: '/home/linuxbrew/.linuxbrew/bin'

- name: Install tig through homebrew
  community.general.homebrew:
    name: tig
    state: present
    path: '/home/linuxbrew/.linuxbrew/bin'

