---

- name: create sources/admin directory if it not exists
  ansible.builtin.file:
    path: "{{ sources_adm }}"
    state: directory

- name: ensure that there is a bin directory
  ansible.builtin.file:
    path: "{{ user_home }}/bin"
    mode: "0755"
    state: directory

- name: Update apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: install essential packages
  become: true
  apt:
    name: "{{ item }}"
  loop:
    - build-essential
    - make
    - libncurses-dev
    - git
    - ack
    - python-pip
    - python3-pip
