---

- name: create sources/admin directory if it not exists
  ansible.builtin.file:
    path: "{{ sources_adm }}"
    state: directory

- name: ensure that there is a bin directory
  ansible.builtin.file:
    path: "{{ user_home }}/bin"
    mode: "0755"
    state: directory

- name: Update apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: install essential packages
  become: true
  apt:
    name: "{{ item }}"
  loop:
    - build-essential
    - make
    - libncurses-dev
    - git
    - ack
    - python-pip
    - python3-pip

- name: install common packages, that might be problematic
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - ripgrep
  tags: skip

- name: Remove previous downloaded installfile (idempotence)
  file:
    path: /tmp/homebrew_install.sh
    state: absent

- name: download homebrew
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: /tmp/homebrew_install.sh
    mode: '0750'

- name: Install homebrew
  command: /tmp/homebrew_install.sh

- name: Activate homebrew without restarting
  shell: /home/linuxbrew/.linuxbrew/bin/brew shellenv

- name: Add brew into global PATH environment variable
  become: true
  copy:
    dest: /etc/profile.d/brew_path.sh
    content: 'PATH=$PATH:/home/linuxbrew/.linuxbrew/bin'
