---

- name: create sources directory if it not exists
  ansible.builtin.file:
    path: "{{ sources }}"
    state: directory

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day
  tags: long
