---

- name: create sources/admin directory if it not exists
  ansible.builtin.file:
    path: "{{ sources_adm }}"
    state: directory

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day
  tags: long

- name: install essential packages
  apt:
    name: "{{ item }}" 
  loop:
    - build-essential
    - make 
    - libncurses-dev
    - git
    - ack

- name: install common packages, that might be problematic
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - ripgrep
  tags: skip 
