---

- name: print out env_current
  debug:
    msg: current_env "{{ env_current }}"

- name: print out home directory
  debug:
    msg: user_home "{{ user_home }}"

- import_tasks: homebrew.yml
  tags: homebrew
