---

- name: print out env_current
  debug:
    msg: current_env "{{ env_current }}"

- name: print out home directory
  debug:
    msg: user_home "{{ user_home }}"

- import_tasks: homebrew.yml
  tags: homebrew

- import_tasks: vim.yml
  tags: vim

- import_tasks: tmux.yml
  tags: tmux

- import_tasks: administration.yml
  tags: administration
