---

- name: install prerequisites for tmux (v3.2)
  become: yes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - libevent-dev
    - ncurses-dev
    - automake
    - pkg-config
    - bison
    - byacc

- name: download package file
  get_url:
    url: "https://github.com/tmux/tmux/releases/download/3.3a/tmux-3.3a.tar.gz"
    dest: "/tmp"

- name: unpack package
  unarchive:
    src: "/tmp/tmux-3.3a.tar.gz"
    dest: "/tmp"

- name: run configure
  shell: "./configure"
  args:
    chdir: "/tmp/tmux-3.3a"

- name: run make
  make:
    chdir: "/tmp/tmux-3.3a"

- name: run make install
  make:
    chdir: "/tmp/tmux-3.3a"
    target: install
  become: yes
  become_user: root

- name: move tmux executable to local bin folder
  copy:
    src: "/tmp/tmux-3.3a/tmux"
    dest: "/home/{{ self_user }}/bin/tmux"
    mode: '0744'

- name: remove temp intallation folder
  file:
    path: "/tmp/tmux-3.3a"
    state: absent

- name: remove tar.gz file
  file:
    path: "/tmp/tmux-3.3a.tar.gz"
    state: absent
  tags: mytest

- name: clone repository for tmux resurrect
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tmux-resurrect
    dest: "{{ sources_adm }}/tmux-resurrect"
    update: no

- name: clone repository for tmux-settings
  ansible.builtin.git:
    repo: git@github.com:GitEdvard/tmux_settings.git
    dest: "{{ sources_adm }}/tmux_settings"
    update: no

- name: create a symlink for tmux settings
  ansible.builtin.file:
    src: "{{ sources_adm }}/tmux_settings/tmux.conf"
    dest: "{{ user_home }}/.tmux.conf"
    owner: "{{ self_user }}"
    group: "{{ self_user }}"
    state: link
