---

- name: install tmux old installation
  become: yes
  apt:
    name: tmux
    state: present


- name: install prerequisite for tmux 3.2, libevent-dev (I couldnt do the actual installation from ansible)
  become: yes
  ansible.builtin.apt:
    name: libevent-dev
    state: present

- name: install prerequisit for tmux 3.2, ncurses-dev (I couldnt do the actual installation from ansible)
  become: yes
  ansible.builtin.apt:
    name: ncurses-dev
    state: present

- name: clone repository for tmux resurrect
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tmux-resurrect
    dest: "{{ sources_adm }}/tmux-resurrect"
    update: no

- name: clone repository for tmux-settings
  ansible.builtin.git:
    repo: git@github.com:GitEdvard/tmux_settings.git
    dest: "{{ sources_adm }}/tmux_settings"
    update: no
  tags: now

- name: create a symlink for tmux settings
  ansible.builtin.file:
    src: "{{ sources_adm }}/tmux_settings/tmux.conf"
    dest: "{{ user_home }}/.tmux.conf"
    owner: "{{ self_user }}"
    group: "{{ self_user }}"
    state: link
