- name: fetch vim from git
  git:
    repo: https://github.com/vim/vim.git
    dest: "{{ sources_other }}/vim"
     
- name: Uninstall vim
  apt:
    name: vim
    state: absent

- name: intall compiled vim with support for ruby, python etc. 
  apt:
    name: vim-nox

#- name: run make distclean for idempotency
#  make:
#    chdir: "{{ sources_other }}/vim/src"
#    target: distclean
#
#- name: configure the compilation
#  shell: "{{ sources_other }}/vim/src/configure --with-features=huge --enable-rubyinterp=yes "
#
#- name: run make in vim repo
#  make:
#    chdir: "{{ sources_other }}/vim/src"
#
#- name: make install vim
#  make:
#    chdir: "{{ sources_other }}/vim/src"
#    target: install

