# - name: install nvim through homebrew
#   # requires: ansible-galaxy collection install community.general
#   community.general.homebrew:
#     name: nvim
#     state: present
#     path: '/home/linuxbrew/.linuxbrew/bin'

- name: install ripgrep through homebrew
  # requires: ansible-galaxy collection install community.general
  community.general.homebrew:
    name: ripgrep
    state: present
    path: '/home/linuxbrew/.linuxbrew/bin'

- name: install ctags through homebrew
  # requires: ansible-galaxy collection install community.general
  community.general.homebrew:
    name: ctags
    state: present
    path: '/home/linuxbrew/.linuxbrew/bin'

- name: Install jsonlint through homebrew
  community.general.homebrew:
    name: jsonlint
    state: present
    path: '/home/linuxbrew/.linuxbrew/bin'


