- name: install nvim through homebrew
  # requires: ansible-galaxy collection install community.general
  community.general.homebrew:
    name: nvim
    state: present
    path: '/home/linuxbrew/.linuxbrew/bin'

- name: install ripgrep through homebrew
  # requires: ansible-galaxy collection install community.general
  community.general.homebrew:
    name: ripgrep
    state: present
    path: '/home/linuxbrew/.linuxbrew/bin'

- name: fetch vim from git
  git:
    repo: https://github.com/vim/vim.git
    dest: "{{ sources_other }}/vim"
  tags: skip
  when: false

- name: Uninstall vim
  apt:
    name: vim
    state: absent
  when: false

- name: install compiled vim with support for ruby, python etc.
  become: true
  apt:
    name: vim-nox
  tags: skip
  when: false

- name: fetch nvim executable
  get_url:
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    dest: "/home/{{ self_user }}/bin/nvim"
    mode: '0740'

- name: Create config directory for nvim
  file:
    path: "{{ self_user }}/.config/nvim"
    state: directory

- name: Deploy init.vim file
  copy:
    src: init.vim
    dest: "{{ self_user }}/.config/nvim/init.vim"

- name: Install pynvim for python 3 so that I can install python vim modules
  pip:
    name: pynvim
    extra_args: "--user --upgrade"
    executable: pip3

- name: Install pynvim for python 2
  pip:
    name: pynvim
    extra_args: "--user --upgrade"
    executable: pip

- name: Fetch Jeremy Kahns dotfiles repo
  git:
    repo: https://github.com/jeremyckahn/dotfiles.git
    dest: "{{ sources_test }}/dotfiles"

- name: Fetch Jeremy Kahns vim-docker-env repo
  git:
    repo: https://github.com/jeremyckahn/vim-docker-env.git
    dest: "{{ sources_test }}/vim-docker-env"

- name: Install jsonlint through homebrew
  community.general.homebrew:
    name: jsonlint
    state: present
    path: '/home/linuxbrew/.linuxbrew/bin'

#- name: run make distclean for idempotency
#  make:
#    chdir: "{{ sources_other }}/vim/src"
#    target: distclean
#
#- name: configure the compilation
#  shell: "{{ sources_other }}/vim/src/configure --with-features=huge --enable-rubyinterp=yes "
#
#- name: run make in vim repo
#  make:
#    chdir: "{{ sources_other }}/vim/src"
#
#- name: make install vim
#  make:
#    chdir: "{{ sources_other }}/vim/src"
#    target: install

