- name: Deploy Systems
  hosts: all
  become: true
  tasks:
    - name: Create_user
      user:
        state: present
        shell: /bin/bash
        name: "{{ self_user }}"
        password: "{{ 'Password1' | password_hash('sha512') }}"
        update_password: on_create

    - name: sudo
      copy:
        dest: /etc/sudoers.d/tux
        content: "{{ self_user }} ALL=(root) NOPASSWD: ALL"

    - name: allow password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        insertafter: '^#PasswordAuthentication'
      notify: restart_sshd

    - name: allow ssh forward agent
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^AllowAgentForwarding'
        insertafter: '#AllowAgentForwarding'
        line: AllowAgentForwarding yes
      notify: restart_sshd

    - name: create .ssh directory
      file:
        path: "/home/{{ self_user }}/.ssh"
        state: directory
        mode: u=rwx

    - name: create known_hosts file if it not exists
      file:
        path: "/home/{{ self_user }}/.ssh/known_hosts"
        state: touch
        mode: u=rw

    # ssh-keyscan -t rsa github.com
    - name: Tell the host about the github server it might want to ssh to
      known_hosts:
        path: "/home/{{ self_user }}/.ssh/known_hosts"
        name: 'github.com'
        key: "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="

    - name: Upload sudo config for key forwarding as root
      lineinfile:
        dest: /etc/sudoers.d/ssh_key_forward
        line: 'Defaults env_keep+=SSH_AUTH_SOCK'
        create: yes
        owner: root
        group: root
        mode: "0440"
        state: present
        validate: 'visudo -c -f %s'

    - name: authorized_keys
      authorized_key:
        user: "{{ item }}"
        state: present
        manage_dir: true
        key: "{{ lookup('file', '../vagrant/obj/ssh/local.pub') }}"
      loop:
        - "{{ self_user }}"
        - 'root'

  handlers:
    - name: restart_sshd
      service:
        name: sshd
        state: restarted
