- name: Deploy Systems
  hosts: all
  become: true
  tasks:
    - name: Create_user
      user:
        state: present
        shell: /bin/bash
        name: "{{ self_user }}"
        password: "{{ 'Password1' | password_hash('sha512') }}"
        update_password: on_create
    - name: sudo
      copy:
        dest: /etc/sudoers.d/tux
        content: "{{ self_user }} ALL=(root) NOPASSWD: ALL"
    - name: edit_sshd
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        insertafter: '^#PasswordAuthentication'
      notify: restart_sshd
    - name: authorized_keys
      authorized_key:
        user: "{{ item }}"
        state: present
        manage_dir: true
        key: "{{ lookup('file', '../vagrant/obj/ssh/local.pub') }}"
      loop:
        - "{{ self_user }}"
        - 'root'
  handlers:
    - name: restart_sshd
      service:
        name: sshd
        state: restarted
