# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative "../vagrant/shared"

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  shared_config "self", config
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision "ansible", playbook: "deploy.yaml"
end

