---

- name: clone bashrc contents repository
  ansible.builtin.git:
    repo: git@github.com:GitEdvard/bashrc-contents.git
    dest: "{{ sources_adm }}/bashrc-contents"
    update: no

- name: clone linux settings repository
  ansible.builtin.git:
    repo: git@github.com:GitEdvard/linux-settings.git
    dest: "{{ sources_adm }}/linux-settings"
    version: "{{ linux_settings_branch }}"
    update: no

- name: remove existing .bashrc file
  ansible.builtin.file:
    path: "{{ user_home }}/.bashrc"
    state: absent

- name: create a symlink for the .bashrc file
  ansible.builtin.file:
    src: "{{ sources_adm }}/linux-settings/bashrc"
    dest: "{{ user_home }}/.bashrc"
    owner: "{{ self_user }}"
    group: "{{ self_user }}"
    state: link

- name: create symlink for emacs config
  ansible.builtin.file:
    src: "{{ sources_adm }}/linux-settings/emacs_dir/emacs"
    dest: "{{ user_home }}/.emacs"
    owner: "{{ self_user }}"
    group: "{{ self_user }}"
    state: link

- name: remove existing .profile file
  file:
    path: "{{ user_home }}/.profile"
    state: absent

- name: create a symlink for the .profile file
  ansible.builtin.file:
    src: "{{ sources_adm }}/bashrc-contents/profile_home/profile"
    dest: "{{ user_home }}/.profile"
    owner: "{{ self_user }}"
    group: "{{ self_user }}"
    state: link

- name: create symlink for bin directories
  ansible.builtin.file:
    src: "{{ sources_adm }}/bashrc-contents/{{ item }}"
    dest: "{{ user_home }}/bin/{{ item }}"
    owner: "{{ self_user }}"
    group: "{{ self_user }}"
    state: link
  loop:
    - bin_home
    - bin_work
    - bin_sysman
    - bin_docker
    - bin_miarka

- name: create symlink for completion scripts
  ansible.builtin.file:
    src: "{{ sources_adm }}/bashrc-contents/scripts"
    dest: "{{ user_home }}/scripts"
    owner: "{{ self_user }}"
    group: "{{ self_user }}"
    state: link

- name: create symlinks for config files
  file:
    src: "{{ sources_adm }}/bashrc-contents/{{ item }}"
    dest: "{{ user_home }}/.{{ item }}"
    owner: "{{ self_user }}"
    group: "{{ self_user }}"
    state: link
  loop:
    - ackrc
    - gitignore-system
    - gitconfig
    - ctags

