- name: download and unzip java-sdk 17
  unarchive:
    src: "https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz"
    dest: /home/edvard/bin
    mode: '0744'
    remote_src: yes

- name: download and unzip java-sdk 19
  unarchive:
    src: "https://download.oracle.com/java/19/archive/jdk-19.0.2_linux-x64_bin.tar.gz"
    dest: /home/edvard/bin
    mode: '0744'
    remote_src: yes

- name: Update path to include java 19
  lineinfile:
    path: "{{ user_home }}/sources/admin/bashrc-contents/common-exports"
    regexp: '^export PATH="/home/edvard/bin/jdk"'
    line: 'export PATH="/home/edvard/bin/jdk-19.0.2/bin:$PATH"'

- name: Define java_home for java 19
  lineinfile:
    path: "{{ user_home }}/sources/admin/bashrc-contents/common-exports"
    regexp: '^export JAVA_HOME'
    line: 'export JAVA_HOME="/home/edvard/bin/jdk-19.0.2/"'

- name: create directory for java language server
  file:
    path: "{{ user_home }}/bin/jdt-language-server-latest"
    state: directory

# https://download.eclipse.org/jdtls/snapshots/?d
- name: download and unpack java language server
  unarchive:
    src: "https://download.eclipse.org/jdtls/snapshots/jdt-language-server-latest.tar.gz"
    dest: /home/edvard/bin/jdt-language-server-latest
    mode: '0744'
    remote_src: yes

- name: update path to include the java language server
  lineinfile:
    path: "{{ user_home }}/sources/admin/bashrc-contents/common-exports"
    regexp: ^export PATH="$PATH:~/bin/jdt-language-server-latest/bin"
    line: 'export PATH="$PATH:~/bin/jdt-language-server-latest/bin"'

- name: download and unzip maven
  unarchive:
    src: "https://dlcdn.apache.org/maven/maven-3/3.9.0/binaries/apache-maven-3.9.0-bin.tar.gz"
    dest: /home/edvard/bin
    mode: '0744'
    remote_src: yes

- name: Update path to include maven
  lineinfile:
    path: "{{ user_home }}/sources/admin/bashrc-contents/common-exports"
    regexp: '^export PATH="$PATH:/home/edvard/bin/apache-maven-3.9.0/bin"'
    line: 'export PATH="$PATH:/home/edvard/bin/apache-maven-3.9.0/bin"'

- name: Define maven_home
  lineinfile:
    path: "{{ user_home }}/sources/admin/bashrc-contents/common-exports"
    regexp: '^export MAVEN_HOME="/home/edvard/bin/apache-maven-3.9.0"'
    line: 'export MAVEN_HOME="/home/edvard/bin/apache-maven-3.9.0"'

- name: download and unzip tomcat
  unarchive:
    src: "https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.27/bin/apache-tomcat-10.0.27.tar.gz"
    dest: "{{ user_home }}/bin"
    mode: '0744'
    remote_src: yes
  tags: tomcat

- name: Update path to include tomcat
  lineinfile:
    path: "{{ user_home }}/sources/admin/bashrc-contents/common-exports"
    regexp: '^export PATH="/home/edvard/bin/apache-tomcat"'
    line: 'export PATH="$PATH:/home/edvard/bin/apache-tomcat-10.0.27/bin"'
  tags: tomcat

- import_tasks: java_debug.yml
  tags: java-debug
