- name: install essential packages
  become: true
  apt:
    name: "{{ item }}"
  loop:
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - curl
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    - libxml2-dev
    - libxmlsec1-dev
    - libffi-dev
    - liblzma-dev

- name: install Qt runtime
  become: true
  apt:
    name: "{{ item }}"
  loop:
    - libxcb-xinerama0
    - libqt5x11extras5
    - network-manager
  tags: qt

- name: Install common installations on astrego
  become: true
  script: installations.sh
  tags: thescript
