- name: fetch nvim package file
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/v0.8.1/nvim-linux64.deb"
    dest: "/tmp/nvim-linux64.deb"

- name: install the deb package
  apt:
    deb: "/tmp/nvim-linux64.deb"
    force: yes
  become: yes
  become_user: root

- name: remove the deb package file
  file:
    path: "/tmp/nvim-linux64.deb"
    state: absent

# - name: fetch nvim executable
#   get_url:
#     url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
#     dest: "/home/{{ self_user }}/bin/nvim"
#     mode: '0740'

- name: create personal plugin directory
  file:
    path: "{{ sources_adm }}/VimPlugins"
    state: directory
    mode: '0755'

- name: clone vim related repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version }}"
    update: no
  loop:
    - repo: 'git@github.com:GitEdvard/VimFiles.git'
      dest: "{{ sources_adm }}/VimFiles"
      version: 'develop'
    - repo: 'git@github.com:GitEdvard/VimRoot.git'
      dest: "{{ sources_adm }}/VimRoot"
      version: "{{ vim_root_branch_name }}"
    - repo: 'git@github.com:GitEdvard/test-on-save.nvim.git'
      dest: "{{ sources_adm }}/VimPlugins/test-on-save.nvim"
      version: 'develop'
    - repo: 'git@github.com:GitEdvard/read-settings.nvim.git'
      dest: "{{ sources_adm }}/VimPlugins/read-settings.nvim"
      version: 'develop'
    - repo: 'git@github.com:GitEdvard/trigger-commands.nvim.git'
      dest: "{{ sources_adm }}/VimPlugins/read-settings.nvim"
      version: 'develop'

- name: create a symlink for the .vimrc file
  ansible.builtin.file:
    src: "{{ sources_adm }}/VimRoot/vimrc"
    dest: "{{ user_home }}/.vimrc"
    owner: "{{ self_user }}"
    group: "{{ self_user }}"
    force: yes
    state: link

- name: create a symlink for the .vim directory
  ansible.builtin.file:
    src: "{{ sources_adm }}/VimFiles"
    dest: "{{ user_home }}/.vim"
    owner: "{{ self_user }}"
    group: "{{ self_user }}"
    state: link

- name: Create config directory for nvim
  file:
    path: "{{ user_home }}/.config/nvim"
    state: directory
    owner: "{{ self_user }}"
    group: "{{ self_user }}"

- name: Deploy init.vim file
  copy:
    src: init.vim
    dest: "{{ user_home }}/.config/nvim/init.vim"

- name: Install pynvim for python 3 so that I can install python vim modules
  pip:
    name: pynvim
    extra_args: "--user --upgrade"
    executable: pip3

- name: Install pynvim for python 2
  pip:
    name: pynvim
    extra_args: "--user --upgrade"
    executable: pip

- name: Install pyright language server
  community.general.npm:
    name: pyright
    global: true
  become: yes
  become_user: root

- name: install pylint
  apt:
    name: pylint
    state: present
  become: yes
  become_user: root

- name: Fetch Jeremy Kahns dotfiles repo
  git:
    repo: https://github.com/jeremyckahn/dotfiles.git
    dest: "{{ sources_test }}/dotfiles"

- name: Fetch Jeremy Kahns vim-docker-env repo
  git:
    repo: https://github.com/jeremyckahn/vim-docker-env.git
    dest: "{{ sources_test }}/vim-docker-env"

- import_tasks: virtualenvs.yml
