---

- name: create sources directories if it not exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ sources_adm }}"
    - "{{ sources_test }}"

- name: ensure that there is a bin directory
  ansible.builtin.file:
    path: "{{ user_home }}/bin"
    mode: "0755"
    state: directory

- name: Update apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: install essential packages
  become: true
  apt:
    name: "{{ item }}"
  loop:
    - build-essential
    - make
    - libncurses-dev
    - git
    - ack
    - python3-pip
    - npm
    - nodejs

- name: install nvm
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash

- name: install emacs
  become: true
  apt:
    name: emacs
    state: present

- name: download fzf git repo
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest: "{{ self_user }}/.fzf"
    update: no
  tags: fzf

- name: install fzf
  command: "{{ self_user }}/.fzf/install --all"
  tags: fzf

