---

- name: create sources directories if it not exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ sources_adm }}"
    - "{{ sources_test }}"

- name: Update apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: install essential packages
  become: true
  apt:
    name: "{{ item }}"
  loop:
    - build-essential
    - make
    - libncurses-dev
    - git
    - ack
    - python3-pip
    - python3.10-venv
    - npm
    - nodejs

- name: install nvm
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash

- name: install emacs
  become: true
  apt:
    name: emacs
    state: present

- name: create symlink for emacs config
  ansible.builtin.file:
    src: "{{ sources_adm }}/linux-settings/emacs_dir/emacs"
    dest: "{{ user_home }}/.emacs"
    owner: "{{ self_user }}"
    group: "{{ self_user }}"
    state: link

- name: download fzf git repo
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    depth: 1
    dest: "{{ user_home }}/.fzf"
    update: no
  tags: fzf

- name: install fzf
  command:
    cmd: "{{ user_home }}/.fzf/install --all"
  tags: fzf

